// fake data post
List<Map<String, dynamic>> posts = [
  {
    "id": 1,
    "name": "John Doe",
    "profile": "assets/images/profile1.jpg",
    "time": "1 hr",
    "caption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "likes": 10,
    "comments": [
      "ABC",
      "DEF",
    ],
  },
  {
    "id": 2,
    "name": "Jane Doe",
    "profile": "assets/images/profile2.jpg",
    "time": "2 hrs",
    "caption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "likes": 20,
    "comments": [
      "ABC",
      "DEF",
      "GHI",
      "JKL",
      "DEF",
      "DEF",
    ],
  },
  {
    "id": 3,
    "name": "Steve Doe",
    "profile": "assets/images/profile3.jpg",
    "time": "3 hrs",
    "caption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "likes": 30,
    "comments": [
      "ABC",
      "DEF",
      "GHI",
      "JKL",
      "JKL",
    ],
  },
  {
    "id": 4,
    "name": "Sarah Doe",
    "profile": "assets/images/profile4.jpg",
    "time": "4 hrs",
    "caption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "likes": 40,
    "comments": [
      "ABC",
      "DEF",
    ],
  },
  {
    "id": 5,
    "name": "Mike Doe",
    "profile": "assets/images/profile5.jpg",
    "time": "5 hrs",
    "caption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "likes": 50,
    "comments": [
      "ABC",
      "DEF",
      "GHI",
      "JKL",
      "DEF",
      "DEF",
      "DEF",
      "DEF",
      "DEF",
      "DEF",
      "DEF",
    ],
  },
];
